branch-defaults:
  ebdeployment:
    environment: lms-backend-dev
global:
  application_name: lms-backend
  default_ec2_keyname: tlm-lms-aws1
  default_platform: 64bit Amazon Linux 2015.03 v2.0.1 running Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
