branch-defaults:
  ebdeployment:
    environment: lms-backend-dev
global:
  application_name: lms-backend
  default_ec2_keyname: tlm-lms-aws1
  default_platform: Python 3.4
  default_region: us-west-2
  profile: null
  sc: git
