branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: tlm-lms-backend
  default_ec2_keyname: tlm
  default_platform: Python 2.7
  default_region: us-west-2
  profile: null
  sc: git
